# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define :bifrost do |bifrost|
    bifrost.vm.box = "generic/centos8"
    bifrost.vm.provider :libvirt do |libvirt|
      libvirt.uri = "qemu:///system"
      libvirt.cpus = 4
      libvirt.memory = 16384
      libvirt.nested = true
    end
  end
end
