---
- hosts: all
  tasks:

  - import_tasks: tasks/packages.yml

  - name: Copy gitconfig
    copy: src=gitconfig dest=~/.gitconfig

  - import_tasks: tasks/tox.yml
    tags:
    - checkout

  - import_tasks: tasks/checkout.yml
    tags:
    - checkout

  - import_tasks: tasks/vim.yml

  - name: Create ~/.config/fish
    file: path=~/.config/fish state=directory

  - name: Copy config.fish
    copy: src=config.fish dest=~/.config/fish/config.fish

  - include_tasks: tasks/devstack.yml
    tags:
    - devstack

  - name: Copy templates
    copy: src=templates/{{ item }} dest=~/{{ item }} mode=0644
    with_items:
    - ironic-config.yaml
    tags:
    - quickstart

  - name: Copy scripts
    copy: src=templates/{{ item }} dest=~/{{ item }} mode=0755
    with_items:
    - deploy-ironic.sh
    tags:
    - quickstart
