---
- hosts: all
  tasks:
  - name: Make sure ansible can work
    command: dnf install -y python-dnf
    become: true
    when: ansible_distribution == 'Fedora'

  - name: Install various packages
    package: name={{item}} state=latest
    with_items:
    - python-devel
    - git
    - vim
    - cmake
    - gcc-c++
    - tmux
    - python-virtualenv
    - libffi-devel
    - openssl-devel
    - libselinux-python
    - tmux
    - python-sphinx
    become: true

  - include: tasks/repos.yml
    tags:
    - repos

  - name: Install optional OpenStack packages
    package: name={{item}} state=latest
    with_items:
    - python-pbr
    - python-flake8
    - python-openstackdocstheme
    - python-oslo-sphinx
    become: true
    ignore_errors: yes

  - name: Install various Fedora packages
    package: name={{item}} state=latest
    with_items:
    - the_silver_searcher
    - fzf
    - fish
    - python-tox
    - git-review
    - python-pip
    - python3-devel
    - python3-pip
    become: true
    when: ansible_distribution == 'Fedora'

  - name: Copy gitconfig
    copy: src=gitconfig dest=~/.gitconfig

  - name: Create ~/.config/fish
    file: path=~/.config/fish state=directory

  - name: Copy config.fish
    copy: src=config.fish dest=~/.config/fish/config.fish

  - include: tasks/vim.yml

  - name: Create ~/Projects
    file: path=~/Projects state=directory

  - name: Check out projects I work on
    include: tasks/checkout.yml
    with_items:
    - ironic
    - ironic-inspector
    - python-ironicclient
    - python-ironic-inspector-client
    - ironic-python-agent
    - tripleo-heat-templates
    - tripleo-common
    - python-tripleoclient

  - include: tasks/devstack.yml
    tags:
    - devstack

  - name: Copy templates
    copy: src=templates/{{ item }} dest=~/{{ item }} mode=0644
    with_items:
    - ironic-config.yaml
    tags:
    - quickstart
    - testenv

  - name: Copy scripts
    copy: src=templates/{{ item }} dest=~/{{ item }} mode=0755
    with_items:
    - deploy-ironic.sh
    tags:
    - quickstart
    - testenv
