---
- hosts: all
  tasks:

  - import_tasks: tasks/packages.yml

  - name: Create local binary directory
    file:
      path: ~/.local/bin
      state: directory

  - name: Copy gitconfig
    copy: src=gitconfig dest=~/.gitconfig

  - name: Copy gitignore
    copy: src=gitignore dest=~/.gitignore

  - import_tasks: tasks/clouds.yml
    tags:
    - quickstart

  - import_tasks: tasks/tox.yml
    tags:
    - checkout

  - import_tasks: tasks/checkout.yml
    tags:
    - checkout

  - import_tasks: tasks/golang.yml
    tags:
    - golang

  - import_tasks: tasks/vim.yml

  - name: Create ~/.config/fish
    file: path=~/.config/fish state=directory

  - name: Copy config.fish
    copy: src=config.fish dest=~/.config/fish/config.fish

  - include_tasks: tasks/devstack.yml
    tags:
    - devstack

  - name: Copy templates
    copy: src=templates/{{ item }} dest=~/{{ item }} mode=0644
    with_items:
    - ironic-config.yaml
    tags:
    - quickstart

  - name: Copy scripts
    copy: src=templates/{{ item }} dest=~/{{ item }} mode=0755
    with_items:
    - deploy-ironic.sh
    tags:
    - quickstart

  - name: Copy the gertty script
    copy:
      src: templates/gertty-or-firefox
      dest: /usr/local/bin/gertty-or-firefox
      mode: "0755"
    become: true

  - name: Copy the gertty desktop file
    copy:
      src: templates/gertty-or-firefox.desktop
      dest: /usr/share/applications/gertty-or-firefox.desktop
      mode: "0644"
    become: true
