---
- hosts: all
  tasks:
  - name: Make sure ansible can work
    command: dnf install -y python-dnf
    become: true
    when: ansible_distribution == 'Fedora'

  - name: Install various packages
    package: name={{item}} state=latest
    with_items:
    - python-devel
    - python-flake8
    - git
    - vim
    - cmake
    - gcc-c++
    - tmux
    - python-virtualenv
    - libffi-devel
    - openssl-devel
    - libselinux-python
    - tmux
    become: true

  - name: Install various Fedora packages
    package: name={{item}} state=latest
    with_items:
    - the_silver_searcher
    - fish
    become: true
    when: ansible_distribution == 'Fedora'

  - name: Copy vimrc
    copy: src=vimrc dest=~/.vimrc

  - name: Copy gitconfig
    copy: src=gitconfig dest=~/.gitconfig

  - name: Install Vundle
    git: repo=https://github.com/VundleVim/Vundle.vim
         dest=~/.vim/bundle/Vundle.vim

  - name: Create ~/.config/fish
    file: path=~/.config/fish state=directory

  - name: Copy config.fish
    copy: src=config.fish dest=~/.config/fish/config.fish

  - name: Install vim plugins
    command: vim +PluginInstall +qall

  - name: Build YouCompleteMe plugin
    command: ./install.py chdir=~/.vim/bundle/YouCompleteMe
