---
- hosts: all
  tasks:
  - name: Make sure ansible can work
    command: dnf install -y python-dnf
    become: true
    when: ansible_distribution == 'Fedora'

  - name: Install various packages
    package: name={{item}} state=latest
    with_items:
    - python-devel
    - git
    - vim
    - cmake
    - gcc-c++
    - tmux
    - python-virtualenv
    - libffi-devel
    - openssl-devel
    - libselinux-python
    - tmux
    - python-sphinx
    become: true

  - include: tasks/repos.yml
    tags:
    - repos

  - name: Install optional OpenStack packages
    package: name={{item}} state=latest
    with_items:
    - python-flake8
    - python-openstackdocstheme
    become: true
    ignore_errors: yes

  - name: Install various Fedora packages
    package: name={{item}} state=latest
    with_items:
    - the_silver_searcher
    - fish
    become: true
    when: ansible_distribution == 'Fedora'

  - name: Copy gitconfig
    copy: src=gitconfig dest=~/.gitconfig

  - name: Create ~/.config/fish
    file: path=~/.config/fish state=directory

  - name: Copy config.fish
    copy: src=config.fish dest=~/.config/fish/config.fish

  - include: tasks/vim.yml

  - include: tasks/testing.yml

  - include: tasks/devstack.yml
    tags:
    - devstack
