---
- hosts: all
  tasks:
  - name: Install git
    package: name=git state=latest

  - name: Install vim
    package: name=vim state=latest

  - name: Copy vimrc
    copy: src=vimrc dest=~/.vimrc

  - name: Copy gitconfig
    copy: src=gitconfig dest=~/.gitconfig
