---
- hosts: all
  tasks:

  - import_tasks: tasks/packages.yml

  - name: Create local binary directory
    file:
      path: ~/.local/bin
      state: directory

  - name: Copy gitconfig
    copy: src=gitconfig dest=~/.gitconfig

  - name: Copy gitignore
    copy: src=gitignore dest=~/.gitignore

  - import_tasks: tasks/checkout.yml
    tags:
    - checkout

  - import_tasks: tasks/golang.yml
    tags:
    - golang

  - import_tasks: tasks/vim.yml

  - name: Create ~/.config/fish
    file: path=~/.config/fish state=directory

  - name: Copy config.fish
    copy: src=config.fish dest=~/.config/fish/config.fish

  - include_tasks: tasks/devstack.yml
    tags:
    - devstack
