---

- name: Create ~/Projects
  file: path=~/Projects state=directory

- name: Check out projects I work on
  git: repo=https://git.openstack.org/openstack/{{ item }}
       dest=~/Projects/{{ item }}
       update=no
  with_items:
  - ironic
  - ironic-inspector
  - python-ironicclient
  - python-ironic-inspector-client
  - ironic-python-agent
  - tripleo-heat-templates
  - tripleo-common
  - python-tripleoclient
  - metalsmith

- name: Create tox environments
  shell: PATH="/usr/bin:$HOME/.local/bin" tox -e py27 --notest
  args:
    chdir: ~/Projects/{{ item }}
    creates: ~/Projects/{{ item }}/.tox/py27
  with_items:
    - ironic
    - ironic-inspector
    - metalsmith
    - python-ironicclient
    - python-ironic-inspector-client
    - python-tripleoclient
