---

- set_fact:
    project: "{{ item }}"

- name: Clone {{ project }}
  git: repo=https://git.openstack.org/openstack/{{ project }}
       dest=~/Projects/{{ project }}
       update=no

- name: Create a virtualenv for {{ project }}
  command: virtualenv venv
  args:
    chdir: ~/Projects/{{ project }}
    creates: ~/Projects/{{ project }}/venv
  tags:
  - testenv

- name: Install or update packages in a virtualenv for {{ project }}
  command: venv/bin/pip install {{ item }}
  args:
    chdir: ~/Projects/{{ project }}
  with_items:
  - 'pip>=7.1.0'
  - 'setuptools>=16.0'
  - '-r requirements.txt'
  - '-e .'
  tags:
  - testenv
