---

- name: Clone devstack
  git: repo=https://git.openstack.org/openstack-dev/devstack
       dest=~/devstack
       update=no

- name: Get default configuration
  get_url: url=https://git.openstack.org/cgit/openstack/ironic-inspector/plain/devstack/example.local.conf
           dest=~/devstack/local.conf
           force=no
