---

- name: Clone devstack
  git:
    repo: https://opendev.org/openstack/devstack
    dest: ~/devstack
    update: no

- name: Get default configuration
  get_url:
    url: https://opendev.org/openstack/ironic-inspector/raw/branch/master/devstack/example.local.conf
    dest: ~/devstack/local.conf
    force: no
