---
- name: Install Go
  package:
    name: golang
    state: latest

- name: Install gopls
  command: go get golang.org/x/tools/gopls@latest
  environment:
    GO111MODULE: "on"

- name: Create a symlink to gopls
  file:
    path: ~/.local/bin/gopls
    src: ~/go/bin/gopls
