---

- name: Make sure ansible can work
  command: dnf install -y python-dnf
  become: true
  when: ansible_distribution == 'Fedora'

- name: Install EPEL for CentOS
  package:
    name: epel-release
    state: present
  become: true
  when: ansible_distribution == 'CentOS'

- name: Install various packages
  package:
    name: "{{ packages_all }}"
    state: latest
  become: true

- name: Install packages (RH version)
  package:
    name: "{{ packages_rh }}"
    state: latest
  become: true
  when: ansible_os_family == 'RedHat'

- name: Install packages (Debian version)
  package:
    name: "{{ packages_deb }}"
    state: latest
  become: true
  when: ansible_os_family == 'Debian'

- name: Upgrade everything (RH version)
  command: dnf upgrade -y
  become: true
  when: ansible_os_family == 'RedHat'

- name: Upgrade everything (Debian version)
  command: apt upgrade -y
  environment:
    DEBIAN_FRONTEND: noninteractive
  become: true
  when: ansible_os_family == 'Debian'

- name: Install optional packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages_opt }}"
  become: true
  ignore_errors: yes
