---

- name: Make sure ansible can work
  command: dnf install -y python-dnf
  become: true
  when: ansible_distribution == 'Fedora'

- name: Install EPEL for devstack
  package:
    name: epel-release
    state: present
  become: true
  when: ansible_distribution == 'CentOS'
  tags:
    - devstack

- name: Install various packages
  package: name={{ packages_all }} state=latest
  vars:
    packages_all:
    - git
    - vim
    - cmake
    - gcc-c++
    - tmux
    - libffi-devel
    - openssl-devel
    - python-devel
    - python-virtualenv
  become: true

- include_tasks: repos.yml
  tags:
  - repos

- name: Install optional packages
  package: name={{ item }} state=latest
  with_items:
    - ansifilter
    - bat
    - fish
    - fzf
    - git-review
    - libselinux-python
    - python-pip
    - python-tox
    - python3-devel
    - python3-pip
    - python36-devel
    - python36-pip
    - the_silver_searcher
  become: true
  ignore_errors: yes
