---

- name: Make sure ansible can work
  command: dnf install -y python-dnf
  become: true
  when: ansible_distribution == 'Fedora'

- name: Install EPEL for CentOS
  package:
    name: epel-release
    state: present
  become: true
  when: ansible_distribution == 'CentOS'

- name: Install various packages
  package: name={{ packages_all }} state=latest
  vars:
    packages_all:
    - cmake
    - git
    - golang
    - guestfs-tools
    - make
    - python3
    - qemu-kvm
    - tmux
    - vim
    - virt-install
  become: true

- name: Install packages (RH version)
  package: name={{ packages_all }} state=latest
  vars:
    packages_all:
    - gcc-c++
    - libffi-devel
    - libpq-devel
    - libvirt-daemon
    - openssl-devel
    - python3-devel
    - python3-libselinux
  become: true
  when: ansible_os_family == 'RedHat'

- name: Install packages (Ubuntu version)
  package: name={{ packages_all }} state=latest
  vars:
    packages_all:
    - build-essential
    - libffi-dev
    - libssl-dev
    - libpq-dev
    - libvirt-daemon-system
    - python3-dev
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Upgrade everything (RH version)
  command: dnf upgrade -y
  become: true
  when: ansible_os_family == 'RedHat'

- name: Upgrade everything (Ubuntu version)
  command: apt upgrade -y
  environment:
    DEBIAN_FRONTEND: noninteractive
  become: true
  when: ansible_distribution == 'Ubuntu'

- include_tasks: repos.yml
  tags:
    - repos

- name: Install optional packages
  package: name={{ item }} state=latest
  with_items:
    - ansifilter
    - bat
    - fd-find
    - fish
    - fzf
    - git-review
    - python3-pip
    - python3-tox
    - python3-flake8
    - the_silver_searcher
  become: true
  ignore_errors: yes
