---

- name: Make sure ansible can work
  command: dnf install -y python-dnf
  become: true
  when: ansible_distribution == 'Fedora'

- name: Install various packages
  package: name={{ packages_all }} state=latest
  vars:
    packages_all:
    - python-devel
    - git
    - vim
    - cmake
    - gcc-c++
    - tmux
    - python-virtualenv
    - libffi-devel
    - openssl-devel
    - libselinux-python
    - tmux
    - python-sphinx
  become: true

- include_tasks: repos.yml
  tags:
  - repos

- name: Install optional OpenStack packages
  package: name={{ packages_os }} state=latest
  vars:
    packages_os:
    - python-pbr
    - python-flake8
    - python-openstackdocstheme
    - python-oslo-sphinx
  become: true
  ignore_errors: yes

- name: Install various Fedora packages
  package: name={{ packages_fedora }} state=latest
  vars:
    packages_fedora:
    - the_silver_searcher
    - fzf
    - fish
    - python-tox
    - git-review
    - python-pip
    - python3-devel
    - python3-pip
  become: true
  when: ansible_distribution == 'Fedora'
