---

- name: Clone tripleo-repos
  git:
    repo: https://git.openstack.org/openstack-infra/tripleo-repos
    dest: /tmp/tripleo-repos

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-virtualenv
    - yum-plugin-priorities
  become: true

- name: Create virtualenv for tripleo-repos
  command: virtualenv /tmp/tripleo-repos/venv
  creates: /tmp/tripleo-repos/venv

- name: Install tripleo-repos into virtualenv
  command: /tmp/tripleo-repos/venv/bin/pip install -e /tmp/tripleo-repos
  creates: /tmp/tripleo-repos/venv/bin/tripleo-repos

- name: Install repositories for the given release
  command: /tmp/tripleo-repos/venv/bin/tripleo-repos {{ openstack_release }}

- name: Update all packages
  command: yum update -y
  become: true

- name: Install OpenStack clients
  package: name={{item}} state=latest
  with_items:
  - python-openstackclient
  - python-ironicclient
  - python-tripleoclient
  become: true
