---

- name: Create ~/Projects
  file: path=~/Projects state=directory

- name: Clone a few things I tend to work on
  git: repo=https://git.openstack.org/openstack/{{item}}
       dest=~/Projects/{{item}}
       update=no
  with_items:
  - ironic
  - ironic-inspector
  - python-ironicclient
  - python-ironic-inspector-client
  - ironic-python-agent
  - tripleo-heat-templates
  - tripleo-common
  - python-tripleoclient
