---

- name: Copy vimrc
  copy: src=vimrc dest=~/.vimrc

- name: Install Vundle
  git: repo=https://github.com/VundleVim/Vundle.vim
       dest=~/.vim/bundle/Vundle.vim

- name: Install vim plugins
  command: vim +PluginInstall +qall

- name: Find YouCompleteMe directory
  stat: path=~/.vim/bundle/YouCompleteMe
  register: ycm

- name: Build YouCompleteMe plugin
  command: ./install.py chdir=~/.vim/bundle/YouCompleteMe
  when: ycm.stat.exists == True
