---

- name: Copy vimrc
  copy: src=vimrc dest=~/.vimrc

- name: Create vim directories
  file:
    path: ~/.vim/{{ item }}
    state: directory
  loop:
    - autoload
    - bundle

- name: Install Plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: Install vim plugins
  command: vim +PlugInstall +qall
